version: '3.8'
services:
  caddy:
    restart: always
    build:
      context: ./caddy
      dockerfile: ./caddy.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      BROKER_URL: http://backend
      WDS_SOCKET_PORT: 0

  backend:
    build:
      context: ./backend
      dockerfile: ./backend.dockerfile
    restart: always
    ports:
      - '8080:8080'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DBSOURCE: 'mongodb://mongo:27017'
      SERVERADDRESS: ':8080'
      PAYPAL_CLIENT_ID: 'ARWtacu1M4CF6e3mbctUCHee54SIRtdZ3_w42UyZPq12lYlK1DRByaQ8S3fd15s6CxA74FWBRIEfMJY7'
      STRIPE_PUBLIC_KEY: 'pk_test_51Ll3OsJgkATjBHAIpFaAILuHKGgFBEtjmjgQ7VBxMxQnpLoDLlUh6nJsyvhrBvhWlCuZdEHWarOHKP33shQPdvdC00YFrICzCQ'
      STRIPE_SECRET_KEY: 'sk_test_51Ll3OsJgkATjBHAINOxdXg9Hdsp0PWdpyIxzGfa3NsnwxIqTwuZby5Cqx9K45zS5TOVOwWOa070VVYDEKCjnYJGt005tIWim7d'
      CLOUDINARY_NAME: 'dgzsfz6ja'
      CLOUDINARY_KEY: '7138823335XXXXX'
      CLOUDINARY_SECRET: '94Vs3LDyJPSpM3diwuX-XXXXXXX'

  mongo:
    image: 'mongo:4.2.24-bionic'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ecommerces
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./backend/db/db-data/mongo/:/data/db
